version: '3'

services:

  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: college_events
    volumes:
      - ./college_events.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
